[build]
  base = "/"
  publish = "dist"
  command = "npx pnpm install --shamefully-hoist --store=node_modules/.pnpm-store --frozen-lockfile && npm run build"

[build.environment]
  NPM_FLAGS = "--version"
