[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[build]
  publish = ".dist"
  command = "pnpm run build || ( npm install pnpm && pnpm run build )"

[build.environment]
  NPM_FLAGS = "--version"
